
meta_product_name: "AhmedKucuk"
meta_title: "Ahmed Kucuk - Web developer"
meta_description: "FullStack Web Developer. Everything you need in one place. I will design, code and publish your web page in short period from scratch. Everything is my code 100/100 rated in Google speed insight, NO WORDPRESS just profesional coding. "
meta_image: "cover.webp" # should exist in `app/assets/images/`
